language: rust
sudo: 9000
dist: trusty
rust:
  - nightly
os:
  - linux
  - osx

env:
  - FEATURES=""
  - FEATURES="--features debugmozjs"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install ccache yasm; fi

script:
  - ccache -z
  - CCACHE=$(which ccache) travis_wait cargo build --verbose $FEATURES
  - CCACHE=$(which ccache) cargo test --verbose $FEATURES
  - ccache -s

notifications:
  webhooks: http://build.servo.org:54856/travis

cache: ccache
