[package]
name = "encoding-index-japanese"
version = "1.20141219.6"
authors = ["Kang Seonghoon <public+rust@mearie.org>"]

description = "Index tables for Japanese character encodings"
homepage = "https://github.com/lifthrasiir/rust-encoding"
readme = "../../../README.md"
license = "CC0-1.0"

[lib]
name = "encoding_index_japanese"
path = "lib.rs"

[features]
no-optimized-legacy-encoding = []

[dependencies.encoding_index_tests]
# TODO consider using dev-dependencies instead (Cargo issue #860)
version = "0.1.5"
path = "../tests"

[profile.test]
# `test_correct_table` tests tend to be especially slow
opt-level = 1
