[package]
name = "compression-bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
benchlib = { path = "../../benchlib", features = ["compression"] }
brotli = "3.3.4"

[workspace]
