[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "site"
version = "0.1.0"
edition = '2018'

[dependencies]
env_logger = "0.7"
anyhow = "1"
thiserror = "1"
futures = "0.3"
tokio = { version = "0.2", features = ["macros"] }
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = { version = "1", features = ["raw_value"] }
hyper = "0.13"
headers = "0.3"
http = "0.2"
chrono = "0.4"
rmp-serde = "0.14.2"
semver = "0.9"
ring = "0.16.10"
hex = "0.4.2"
regex = "1"
lazy_static = "1"
reqwest = { version = "0.10", features = ["json"] }
toml = "0.5"
jemallocator = "0.3"
jemalloc-ctl = "0.3"
rust_team_data = { git = "https://github.com/rust-lang/team" }
parking_lot = "0.10"
snap = "1"
rustc-artifacts = "0.2"
itertools = "0.9"

[dependencies.collector]
path = "../collector"

[dev-dependencies]
lazy_static = "1"
pretty_assertions = "0.6"
