[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "site"
version = "0.1.0"
edition = '2018'

[dependencies]
env_logger = "0.6"
failure = "0.1"
futures = "0.1.13"
futures-cpupool = "0.1.5"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
hyper = "0.11"
antidote = "1.0"
chrono = "0.4"
flate2 = "1.0.6"
rmp-serde = "0.13.7"
semver = "0.9"
ring = "0.14.0"
hex = "0.3.2"
regex = "1"
lazy_static = "1"
reqwest = "0.9"
toml = "0.4"
jemallocator = "0.1.9"
jemalloc-ctl = "0.2"
rust_team_data = { git = "https://github.com/rust-lang/team" }

[dependencies.collector]
path = "../collector"

[dev-dependencies]
lazy_static = "1"
pretty_assertions = "0.6"
