[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "site"
version = "0.1.0"
edition = '2018'

[dependencies]
env_logger = "0.8"
anyhow = "1"
thiserror = "1"
futures = "0.3"
tokio = { version = "1.6", features = ["macros", "time"] }
log = "0.4"
serde = { version = "1", features = ["rc"] }
serde_derive = "1"
serde_json = "1"
hyper = { version = "0.14", features = ["server", "stream"] }
headers = "0.3"
http = "0.2"
home = "0.5"
chrono = "0.4"
rmp-serde = "0.15"
brotli = "3.3.3"
semver = "1.0"
ring = "0.16.10"
hex = "0.4.2"
regex = "1"
lazy_static = "1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
toml = "0.5"
rust_team_data = { git = "https://github.com/rust-lang/team" }
parking_lot = "0.11"
snap = "1"
itertools = "0.10"
hashbrown = { version = "0.11", features = ["serde"] }
arc-swap = "1.3"
rusqlite = { version = "0.25", features = ["bundled"] }
async-trait = "0.1"
database = { path = "../database" }
bytes = "1.0"
url = "2"
analyzeme = { git = "https://github.com/rust-lang/measureme", branch = "stable" }
tar = "0.4"
inferno = { version="0.10", default-features = false }
mime = "0.3"
prometheus = "0.12"
uuid = { version = "0.8.2", features = ["v4"] }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.3"
jemalloc-ctl = "0.3"

[dependencies.collector]
path = "../collector"

[dev-dependencies]
lazy_static = "1"
pretty_assertions = "0.7"
