[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "rustc-perf"
version = "0.1.0"

[dependencies]
env_logger = "0.4.2"
error-chain = "0.11.0-rc.2"
futures = "0.1.13"
futures-cpupool = "0.1.5"
log = "0.3.6"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
hyper = "0.11"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dev-dependencies]
lazy_static = "0.2.1"
pretty_assertions = "0.1.2"
