[package]
authors = ["Mark-Simulacrum <mark.simulacrum@gmail.com>", "Nicholas Cameron <ncameron@mozilla.com>", "The rustc-perf contributors"]
name = "site"
version = "0.1.0"
edition = '2018'

[dependencies]
env_logger = "0.6"
failure = "0.1"
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
hyper = "0.12"
headers = "0.2.1"
http = "0.1.17"
chrono = "0.4"
rmp-serde = "0.13.7"
semver = "0.9"
ring = "0.16.0"
hex = "0.3.2"
regex = "1"
lazy_static = "1"
reqwest = "0.9"
toml = "0.5"
jemallocator = "0.3"
jemalloc-ctl = "0.3"
rust_team_data = { git = "https://github.com/rust-lang/team" }
bincode = "1"
parking_lot = "0.9"

[dependencies.collector]
path = "../collector"

[dev-dependencies]
lazy_static = "1"
pretty_assertions = "0.6"
