[package]
name = "matrix_inverse"
version = "0.1.0"
authors = ["Gonzalo Brito Gadeschi <gonzalobg88@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd = { path = "../.." }

[lib]
name = "matrix_inverse_lib"
path = "src/lib.rs"
