[package]
name = "termcolor"
version = "0.3.6"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
A simple cross platform library for writing colored text to a terminal.
"""
documentation = "https://docs.rs/termcolor"
homepage = "https://github.com/BurntSushi/ripgrep/tree/master/termcolor"
repository = "https://github.com/BurntSushi/ripgrep/tree/master/termcolor"
readme = "README.md"
keywords = ["windows", "win", "color", "ansi", "console"]
license = "Unlicense/MIT"

[lib]
name = "termcolor"
bench = false

[target.'cfg(windows)'.dependencies]
wincolor = { version = "0.1.6", path = "../wincolor" }
