[package]
name = "spectral_norm"
version = "0.1.0"
authors = ["gnzlbg <gonzalobg88@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd = { path = "../.." }

[[bin]]
name = "spectral_norm"
path = "src/main.rs"

[lib]
name = "spectral_norm_lib"
path = "src/lib.rs"
