[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "collector"
version = "0.1.0"

[dependencies]
clap = "2.25"
env_logger = "0.5"
failure = "0.1.1"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
tempdir = "0.3"
libc = "0.2"
chrono = "0.4"
cargo_metadata = "0.4"
lazy_static = "1"

[dependencies.rust_sysroot]
git = "https://github.com/Mark-Simulacrum/bisect-rust.git"
optional = false

[[bin]]
name = "collector"
path = "src/bin/rustc-perf-collector/main.rs"

[[bin]]
name = "rustc-fake"
path = "src/bin/rustc-fake.rs"
