[package]
authors = ["Mark Simulacrum <mark.simulacrum@gmail.com>"]
name = "rustc-perf-collector"
version = "0.1.0"

[dependencies]
clap = "2.25"
env_logger = "0.4.0"
error-chain = "0.11.0-rc.2"
log = "0.3"
reqwest = "0.6.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tempdir = "0.3"
libc = "0.2"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.rust_sysroot]
git = "https://github.com/Mark-Simulacrum/bisect-rust.git"
optional = false

[[bin]]
name = "rustc-perf-collector"
path = "src/bin/rustc-perf-collector/main.rs"

[[bin]]
name = "rustc-fake"
path = "src/bin/rustc-fake.rs"
